[package]
name = "process-collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
procfs = "0.17.0"
prometheus-client = { path = "../" }

[target.'cfg(unix)'.dependencies]
libc = "^0.2"
